
package br.gov.ce.sefaz.pge.wsdl.inscricao;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://inscricao.wsdl.pge.sefaz.ce.gov.br/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private br.gov.ce.sefaz.pge.wsdl.inscricao.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, br.gov.ce.sefaz.pge.wsdl.inscricao.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, br.gov.ce.sefaz.pge.wsdl.inscricao.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.gov.ce.sefaz.pge.wsdl.inscricao.Exception
     */
    public br.gov.ce.sefaz.pge.wsdl.inscricao.Exception getFaultInfo() {
        return faultInfo;
    }

}
