
package br.gov.ce.sefaz.pge.wsdl.inscricao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InfoDaeService", targetNamespace = "http://inscricao.wsdl.pge.sefaz.ce.gov.br/", wsdlLocation = "http://www3.sefaz.ce.gov.br/InfoDaeService/InfoDae?wsdl")
public class InfoDaeService
    extends Service
{

    private final static URL INFODAESERVICE_WSDL_LOCATION;
    private final static WebServiceException INFODAESERVICE_EXCEPTION;
    private final static QName INFODAESERVICE_QNAME = new QName("http://inscricao.wsdl.pge.sefaz.ce.gov.br/", "InfoDaeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www3.sefaz.ce.gov.br/InfoDaeService/InfoDae?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INFODAESERVICE_WSDL_LOCATION = url;
        INFODAESERVICE_EXCEPTION = e;
    }

    public InfoDaeService() {
        super(__getWsdlLocation(), INFODAESERVICE_QNAME);
    }

    public InfoDaeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INFODAESERVICE_QNAME, features);
    }

    public InfoDaeService(URL wsdlLocation) {
        super(wsdlLocation, INFODAESERVICE_QNAME);
    }

    public InfoDaeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INFODAESERVICE_QNAME, features);
    }

    public InfoDaeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoDaeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InfoDae
     */
    @WebEndpoint(name = "InfoDaePort")
    public InfoDae getInfoDaePort() {
        return super.getPort(new QName("http://inscricao.wsdl.pge.sefaz.ce.gov.br/", "InfoDaePort"), InfoDae.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoDae
     */
    @WebEndpoint(name = "InfoDaePort")
    public InfoDae getInfoDaePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://inscricao.wsdl.pge.sefaz.ce.gov.br/", "InfoDaePort"), InfoDae.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INFODAESERVICE_EXCEPTION!= null) {
            throw INFODAESERVICE_EXCEPTION;
        }
        return INFODAESERVICE_WSDL_LOCATION;
    }

}
